version: '3.4'

services:
  circlecdn:
    image: ${DOCKER_REGISTRY}circle_cdn:${TAG}
    build:
      context: .
      dockerfile: CircleCDN/Dockerfile
    volumes:
      - /public:/public

  circlegetway:
    image: ${DOCKER_REGISTRY}public_cdn:${TAG}
    build:
      context: .
      dockerfile: Getway/Dockerfile
    volumes:
      - /routes:/app/Routes

  staticenvironment:
    image: ${DOCKER_REGISTRY}staticenvironment:${TAG}
    build:
      context: .
      dockerfile: StaticEnvironment/Dockerfile
    volumes:
      - /public:/usr/share/nginx/html


volumes:
  staticenvironment: